### PR TITLE
fixing project as a gift

### PR DESCRIPTION
**Pull request by SouhailM07**
_Enjoy your new project_ , Feel free to tell me how did you find it  .

### CODE REVIEW

**Review by ahmed-hazem-1 — COMMENTED** [review]
wow! you fix the issue of width of"par" div ,i have few questions to increase my knowledge
1- why you replace the font links with anther style of link? is it make a problem or it more proffesional?

2- is the "article , section " attributes is better than div ?

i like the idea of making minimum height for main div 😊, and font optical sizing is auto 😊,the best part is the shadow hover 😊❤️,thank you very much souhail 😊❤️

**Comment by SouhailM07** [comment]
Your welcome brother  😊❤️,  when i saw your bio , you gaved me hope that there still some light in this world at this time , and to anwer your questions , :
1- i didn't update the fonts links , i removed the svg and replace it with img using src 
2- article and section elements are called semantic elements , they are used to help in accessbility , to help the blind people to use screen readers in your websites .
image

**Comment by ahmed-hazem-1** [comment]
there are many people still light like you too😊.
the accessibility  i forget it at all😮, thanks for remembering me😊❤️.
what is the name of website that analyze the webpages? i want to check my future webpages on it

**Comment by SouhailM07** [comment]
You are not ready for it, brother. I'm afraid that if you focus on those things while still a beginner, you could develop obsessive-compulsive disorder from the numbers , you must focus on learning the basics then when you get better , you can focus on advanced things like this , Good luck 👍 .

**Comment by ahmed-hazem-1** [comment]
you are right😊,i must focus on basics then improve my skills, thank you very much brother😊❤️❤️

**Comment by SouhailM07** [comment]
You're welcome brother 👍 .

**Pull request merged**
